/** Single source for language picker rows (onboarding + parent settings). */
export const LANGUAGE_OPTIONS = [
  {
    code: 'en',
    labelKey: 'parent.languageEnglish',
    flag: '🇬🇧',
    nativeLabel: 'English',
    nativeRegion: 'United Kingdom',
    englishRegion: 'United Kingdom',
  },
  {
    code: 'is',
    labelKey: 'parent.languageIcelandic',
    flag: '🇮🇸',
    nativeLabel: 'Íslenska',
    nativeRegion: 'Ísland',
    englishRegion: 'Iceland',
  },
  {
    code: 'es',
    labelKey: 'parent.languageSpanish',
    flag: '🇪🇸',
    nativeLabel: 'Español',
    nativeRegion: 'España',
    englishRegion: 'Spain',
  },
  {
    code: 'de',
    labelKey: 'parent.languageGerman',
    flag: '🇩🇪',
    nativeLabel: 'Deutsch',
    nativeRegion: 'Deutschland',
    englishRegion: 'Germany',
  },
  {
    code: 'fr',
    labelKey: 'parent.languageFrench',
    flag: '🇫🇷',
    nativeLabel: 'Français',
    nativeRegion: 'France',
    englishRegion: 'France',
  },
  {
    code: 'pt',
    labelKey: 'parent.languagePortuguese',
    flag: '🇵🇹',
    nativeLabel: 'Português',
    nativeRegion: 'Portugal',
    englishRegion: 'Portugal',
  },
  {
    code: 'pl',
    labelKey: 'parent.languagePolish',
    flag: '🇵🇱',
    nativeLabel: 'Polski',
    nativeRegion: 'Polska',
    englishRegion: 'Poland',
  },
];
