import { StyleSheet } from 'react-native';

export function createHomeStyles(c) {
  return StyleSheet.create({
    loadingRoot: {
      flex: 1,
      backgroundColor: c.bg,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    loadingText: {
      fontSize: 16,
      color: c.textSecondary,
      fontWeight: '600',
    },
    safe: {
      flex: 1,
      backgroundColor: c.bg,
    },
    parentLockRoot: {
      flex: 1,
      backgroundColor: c.bg,
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    lockOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    lockCard: {
      backgroundColor: c.surface,
      borderRadius: 20,
      padding: 22,
      borderWidth: 1,
      borderColor: c.border,
    },
    lockTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: c.text,
      marginBottom: 8,
    },
    lockSub: {
      fontSize: 15,
      color: c.textSecondary,
      lineHeight: 21,
      marginBottom: 16,
    },
    lockError: {
      color: c.error,
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
    },
    lockActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 12,
      marginTop: 8,
    },
    lockCancel: {
      paddingVertical: 12,
      paddingHorizontal: 16,
    },
    lockCancelText: {
      fontSize: 16,
      fontWeight: '600',
      color: c.textSecondary,
    },
    lockContinue: {
      backgroundColor: c.primary,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
    },
    lockContinueText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#fff',
    },
    scroll: {
      paddingBottom: 132,
      paddingHorizontal: 20,
    },
    profileEntryCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      backgroundColor: c.surface,
      borderRadius: 26,
      paddingVertical: 16,
      paddingHorizontal: 18,
      marginBottom: 18,
      borderWidth: 3,
      borderColor: c.primary,
      shadowColor: c.cardShadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 3,
    },
    profileEntryCardPressed: {
      opacity: 0.92,
    },
    profileEntryTextCol: {
      flex: 1,
      minWidth: 0,
    },
    whosPlayingLabel: {
      fontSize: 15,
      fontWeight: '800',
      color: c.primaryDark,
      letterSpacing: 0.2,
      marginBottom: 4,
    },
    profileEntryName: {
      fontSize: 22,
      fontWeight: '800',
      color: c.text,
    },
    profileEntryHint: {
      fontSize: 15,
      color: c.textSecondary,
      fontWeight: '600',
      marginTop: 4,
    },
    header: {
      alignItems: 'center',
      paddingTop: 10,
      paddingBottom: 22,
    },
    kicker: {
      fontSize: 17,
      fontWeight: '800',
      color: c.primaryDark,
      letterSpacing: 0.2,
    },
    starHero: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: 8,
    },
    starCount: {
      fontSize: 56,
      fontWeight: '900',
      color: c.text,
      fontVariant: ['tabular-nums'],
    },
    hint: {
      marginTop: 14,
      fontSize: 17,
      color: c.textMuted,
      textAlign: 'center',
      maxWidth: 320,
      lineHeight: 24,
      fontWeight: '600',
    },
    section: {
      marginBottom: 28,
    },
    sectionTitle: {
      fontSize: 26,
      fontWeight: '800',
      color: c.text,
      marginBottom: 6,
    },
    sectionSub: {
      fontSize: 16,
      color: c.textSecondary,
      marginBottom: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    subSectionHeading: {
      fontSize: 19,
      fontWeight: '800',
      color: c.primaryDark,
      marginBottom: 12,
      marginTop: 6,
    },
    subSectionHeadingSpaced: {
      marginTop: 22,
    },
    shopScroll: {
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 132,
    },
    shopStarsBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      backgroundColor: c.surface,
      borderRadius: 24,
      padding: 18,
      marginBottom: 18,
      borderWidth: 3,
      borderColor: c.starPillBg,
      shadowColor: c.cardShadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
    },
    shopStarsTextCol: {
      flex: 1,
      minWidth: 0,
    },
    shopStarsLabel: {
      fontSize: 16,
      fontWeight: '800',
      color: c.primaryDark,
    },
    shopStarsValue: {
      fontSize: 38,
      fontWeight: '900',
      color: c.text,
      fontVariant: ['tabular-nums'],
    },
    shopStarsForName: {
      fontSize: 14,
      fontWeight: '600',
      color: c.textSecondary,
      marginTop: 4,
    },
    shopEntryCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: c.surface,
      borderRadius: 22,
      paddingVertical: 16,
      paddingHorizontal: 18,
      marginTop: 4,
      marginBottom: 8,
      borderWidth: 3,
      borderColor: c.primary,
      gap: 14,
    },
    shopEntryIconWrap: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: c.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    shopEntryTextCol: {
      flex: 1,
    },
    shopEntryTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: c.text,
    },
    shopEntrySub: {
      fontSize: 14,
      color: c.textSecondary,
      marginTop: 4,
      lineHeight: 20,
    },
    taskCard: {
      backgroundColor: c.surface,
      borderRadius: 22,
      paddingVertical: 18,
      paddingHorizontal: 18,
      minHeight: 80,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 2,
      borderColor: c.border,
      shadowColor: c.cardShadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 3,
    },
    completedCard: {
      backgroundColor: c.completedBg,
      borderRadius: 22,
      paddingVertical: 16,
      paddingHorizontal: 18,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 14,
      borderWidth: 2,
      borderColor: c.completedBorder,
    },
    completedIconWrap: {
      paddingTop: 2,
    },
    completedBody: {
      flex: 1,
    },
    completedTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: c.completedTitle,
      marginBottom: 8,
    },
    earnedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    earnedText: {
      fontSize: 17,
      fontWeight: '700',
      color: c.earnedText,
    },
    completedLimitNote: {
      fontSize: 14,
      color: c.textSecondary,
      marginBottom: 12,
      lineHeight: 20,
    },
    taskCardPressed: {
      transform: [{ scale: 0.97 }],
      opacity: 0.96,
    },
    taskRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      flex: 1,
      paddingRight: 8,
    },
    taskTitle: {
      fontSize: 19,
      fontWeight: '700',
      color: c.text,
      flex: 1,
      lineHeight: 26,
    },
    taskMeta: {
      minWidth: 88,
      alignItems: 'flex-end',
    },
    starPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: c.starPillBg,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: c.starGold,
    },
    starPillText: {
      fontWeight: '800',
      color: c.starPillText,
      fontSize: 16,
    },
    rewardCard: {
      backgroundColor: c.surface,
      borderRadius: 22,
      padding: 18,
      minHeight: 84,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 14,
      borderWidth: 2,
      borderColor: c.border,
      shadowColor: c.cardShadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
    },
    rewardInfo: {
      flex: 1,
    },
    rewardTitle: {
      fontSize: 19,
      fontWeight: '700',
      color: c.text,
      lineHeight: 26,
    },
    costRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 6,
    },
    costText: {
      fontSize: 16,
      fontWeight: '700',
      color: c.costText,
    },
    empty: {
      fontSize: 16,
      color: c.textSecondary,
      fontStyle: 'italic',
      lineHeight: 24,
      fontWeight: '600',
    },
    parentFab: {
      position: 'absolute',
      right: 20,
      bottom: 24,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: c.fabBg,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    parentFabText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 15,
    },
    modalSafe: {
      flex: 1,
      backgroundColor: c.bg,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      backgroundColor: c.surface,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: c.text,
    },
    modalClose: {
      fontSize: 17,
      fontWeight: '600',
      color: c.primary,
    },
    modalScroll: {
      padding: 20,
      paddingBottom: 40,
    },
    modalSection: {
      fontSize: 13,
      fontWeight: '700',
      color: c.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginBottom: 10,
    },
    modalSectionSpaced: {
      marginTop: 24,
    },
    langRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 4,
    },
    langChip: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 12,
      backgroundColor: c.surfaceMuted,
      borderWidth: 2,
      borderColor: 'transparent',
      alignItems: 'center',
    },
    langChipActive: {
      backgroundColor: c.surface,
      borderColor: c.primary,
    },
    langChipLabel: {
      fontSize: 15,
      fontWeight: '600',
      color: c.textSecondary,
    },
    langChipLabelActive: {
      color: c.primaryDark,
    },
    switchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 16,
      marginBottom: 4,
      paddingVertical: 4,
    },
    switchLabelWrap: {
      flex: 1,
    },
    switchLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: c.text,
    },
    switchSub: {
      fontSize: 14,
      color: c.textSecondary,
      marginTop: 4,
      lineHeight: 20,
    },
    resetStarsSub: {
      fontSize: 15,
      color: c.textSecondary,
      lineHeight: 21,
      marginBottom: 12,
    },
    dangerButton: {
      backgroundColor: c.dangerButtonBg,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: c.error,
    },
    dangerButtonText: {
      color: c.error,
      fontWeight: '700',
      fontSize: 16,
    },
    input: {
      backgroundColor: c.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 16,
      marginBottom: 10,
      color: c.text,
    },
    primaryButton: {
      backgroundColor: c.primary,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 4,
    },
    primaryButtonText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 16,
    },
    secondaryButton: {
      backgroundColor: c.surface,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 4,
      borderWidth: 2,
      borderColor: c.primary,
    },
    secondaryButtonText: {
      color: c.primary,
      fontWeight: '700',
      fontSize: 16,
    },
    changePinFeedback: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
      marginTop: 4,
    },
    changePinOk: {
      color: c.success,
    },
    changePinBad: {
      color: c.error,
    },
    manageRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      gap: 8,
    },
    manageText: {
      flex: 1,
      fontSize: 16,
      color: c.text,
      marginRight: 8,
      minWidth: 0,
    },
    manageActions: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 0,
      gap: 12,
    },
    reuseLink: {
      color: c.primary,
      fontWeight: '600',
      fontSize: 14,
    },
    remove: {
      color: c.error,
      fontWeight: '600',
      fontSize: 15,
    },
  });
}
