import { StyleSheet } from 'react-native';

export function createParentStyles(c) {
  return StyleSheet.create({
    loadingRoot: {
      flex: 1,
      backgroundColor: c.bg,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    loadingText: {
      fontSize: 16,
      color: c.textSecondary,
      fontWeight: '600',
    },
    safe: {
      flex: 1,
      backgroundColor: c.bg,
    },
    parentLockRoot: {
      flex: 1,
      backgroundColor: c.bg,
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    lockCard: {
      backgroundColor: c.surface,
      borderRadius: 20,
      padding: 24,
      borderWidth: 1,
      borderColor: c.borderStrong,
      shadowColor: c.cardShadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    lockTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: c.text,
      marginBottom: 8,
    },
    lockSub: {
      fontSize: 15,
      color: c.textSecondary,
      lineHeight: 22,
      marginBottom: 20,
    },
    lockError: {
      color: c.error,
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 12,
    },
    lockActions: {
      marginTop: 8,
    },
    lockForgotLink: {
      alignSelf: 'flex-end',
      marginTop: -2,
      marginBottom: 6,
      color: c.primary,
      fontSize: 14,
      fontWeight: '700',
    },
    lockCancelForgotButton: {
      marginTop: 8,
    },
    dangerGlassSpacing: {
      marginTop: 8,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 22,
      paddingVertical: 18,
      backgroundColor: c.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: c.text,
    },
    headerAction: {
      fontSize: 16,
      fontWeight: '700',
      color: c.primary,
    },
    subTabBar: {
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: c.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    subTab: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: c.surfaceMuted,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    subTabActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    subTabText: {
      fontSize: 15,
      fontWeight: '700',
      color: c.textSecondary,
    },
    subTabTextActive: {
      color: '#fff',
    },
    scroll: {
      paddingHorizontal: 18,
      paddingTop: 18,
      paddingBottom: 150,
    },
    card: {
      backgroundColor: c.surface,
      borderRadius: 22,
      padding: 22,
      marginBottom: 18,
      borderWidth: 2,
      borderColor: c.border,
      shadowColor: c.cardShadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    cardTitleRow: {
      alignSelf: 'stretch',
      paddingBottom: 12,
      marginBottom: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.borderStrong,
    },
    cardTitle: {
      fontSize: 21,
      fontWeight: '800',
      color: c.primaryDark,
      letterSpacing: 0.25,
    },
    cardDesc: {
      fontSize: 14,
      color: c.textSecondary,
      lineHeight: 20,
      marginTop: 2,
      marginBottom: 16,
    },
    inCardDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.border,
      marginVertical: 18,
    },
    langPickerTrigger: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingVertical: 6,
      paddingHorizontal: 2,
    },
    langPickerFlag: {
      fontSize: 34,
      lineHeight: 40,
    },
    langPickerTextCol: {
      flex: 1,
    },
    langPickerLang: {
      fontSize: 17,
      fontWeight: '700',
      color: c.text,
    },
    langPickerCountry: {
      fontSize: 14,
      color: c.textSecondary,
      marginTop: 2,
    },
    langModalRoot: {
      flex: 1,
      justifyContent: 'flex-end',
    },
    langModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.45)',
    },
    langModalSheet: {
      backgroundColor: c.surface,
      borderTopLeftRadius: 22,
      borderTopRightRadius: 22,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderStrong,
      maxHeight: '72%',
      paddingBottom: 8,
      shadowColor: c.cardShadow,
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 16,
    },
    langModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    langModalTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: c.primary,
      letterSpacing: 0.2,
    },
    langModalList: {
      maxHeight: 400,
    },
    langModalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 20,
      gap: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    langModalRowSelected: {
      backgroundColor: c.surfaceMuted,
    },
    langModalFlag: {
      fontSize: 32,
      lineHeight: 38,
    },
    langModalLabels: {
      flex: 1,
    },
    langModalLangName: {
      fontSize: 17,
      fontWeight: '700',
      color: c.text,
    },
    langModalCountry: {
      fontSize: 14,
      color: c.textSecondary,
      marginTop: 3,
    },
    langModalCheckPlaceholder: {
      width: 26,
      height: 26,
    },
    switchBlock: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 16,
    },
    switchTextCol: {
      flex: 1,
    },
    switchLabel: {
      fontSize: 16,
      fontWeight: '700',
      color: c.text,
    },
    switchSub: {
      fontSize: 14,
      color: c.textSecondary,
      marginTop: 4,
      lineHeight: 20,
    },
    input: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: c.border,
      paddingHorizontal: 16,
      paddingVertical: 15,
      fontSize: 16,
      marginBottom: 12,
      color: c.text,
    },
    inputCompact: {
      marginBottom: 0,
    },
    rowInputs: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 12,
    },
    inputFlex: {
      flex: 1,
    },
    inputStars: {
      width: 96,
    },
    buttonStack: {
      gap: 10,
      marginTop: 4,
    },
    recurrenceRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 12,
    },
    recurrenceChip: {
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 14,
      paddingVertical: 11,
      paddingHorizontal: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    recurrenceChipActive: {
      backgroundColor: c.primary,
      borderColor: c.primaryDark,
    },
    recurrenceChipText: {
      fontSize: 15,
      fontWeight: '700',
      color: c.textSecondary,
    },
    recurrenceChipTextActive: {
      color: '#ffffff',
    },
    listSectionLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: c.textSecondary,
      letterSpacing: 0.3,
      marginBottom: 8,
      marginTop: 4,
    },
    listRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      paddingVertical: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
      gap: 12,
    },
    listRowFirst: {
      borderTopWidth: 0,
      paddingTop: 0,
    },
    listRowText: {
      flex: 1,
      fontSize: 16,
      color: c.text,
      lineHeight: 22,
      minWidth: 0,
    },
    listRowActions: {
      alignItems: 'flex-end',
      gap: 8,
      flexShrink: 0,
    },
    listRowActionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: 12,
    },
    linkText: {
      color: c.primary,
      fontWeight: '600',
      fontSize: 14,
    },
    removeText: {
      color: c.error,
      fontWeight: '600',
      fontSize: 14,
    },
    emptyHint: {
      fontSize: 15,
      color: c.textSecondary,
      fontStyle: 'italic',
      lineHeight: 22,
      paddingVertical: 8,
    },
    mutedNote: {
      fontSize: 14,
      color: c.textSecondary,
      lineHeight: 20,
      marginTop: 8,
      marginBottom: 4,
    },
    changePinFeedback: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
      marginTop: 8,
    },
    changePinOk: {
      color: c.success,
    },
    changePinBad: {
      color: c.error,
    },
    warnCard: {
      borderColor: c.border,
      backgroundColor: c.surfaceMuted,
    },
    editRowBlock: {
      paddingVertical: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    editRowBlockFirst: {
      borderTopWidth: 0,
      paddingTop: 0,
    },
    editFormStarsRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'flex-start',
    },
    editFormStarsInput: {
      width: 100,
    },
    editFormActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 14,
    },
    editFormActionFlex: {
      flex: 1,
    },
    taskItemStack: {
      width: '100%',
    },
    taskItemTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: c.text,
      lineHeight: 24,
    },
    taskItemMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      marginTop: 8,
      gap: 8,
    },
    taskStarBadge: {
      alignSelf: 'flex-start',
      backgroundColor: c.starPillBg,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 12,
    },
    taskStarBadgeText: {
      fontSize: 14,
      fontWeight: '700',
      color: c.starPillText,
    },
    taskRecurrenceBadge: {
      alignSelf: 'flex-start',
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: c.border,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 12,
    },
    taskRecurrenceBadgeText: {
      fontSize: 13,
      fontWeight: '700',
      color: c.textSecondary,
    },
    taskActionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      marginTop: 14,
      gap: 8,
    },
    reusableSavedChip: {
      alignSelf: 'flex-start',
      minHeight: 44,
      paddingVertical: 11,
      paddingHorizontal: 16,
      borderRadius: 14,
      justifyContent: 'center',
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: c.border,
    },
    reusableSavedChipText: {
      fontSize: 14,
      fontWeight: '600',
      color: c.textSecondary,
      textAlign: 'center',
    },
    rewardItemStack: {
      width: '100%',
    },
    rewardItemTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: c.text,
      lineHeight: 22,
    },
    rewardItemFooter: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginTop: 10,
    },
    rewardCostBadge: {
      backgroundColor: c.starPillBg,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 12,
    },
    rewardCostText: {
      fontSize: 14,
      fontWeight: '700',
      color: c.starPillText,
    },
  });
}
