import { StyleSheet } from 'react-native';

export function createSwitchProfileStyles(c) {
  return StyleSheet.create({
    loadingRoot: {
      flex: 1,
      backgroundColor: c.bg,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    loadingText: {
      fontSize: 16,
      color: c.textSecondary,
      fontWeight: '600',
    },
    safe: {
      flex: 1,
      backgroundColor: c.bg,
    },
    scroll: {
      flexGrow: 1,
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headlineBlock: {
      width: '100%',
      alignItems: 'center',
      marginBottom: 24,
      paddingHorizontal: 4,
    },
    headline: {
      fontSize: 30,
      fontWeight: '900',
      color: c.text,
      textAlign: 'center',
      lineHeight: 36,
      maxWidth: 340,
    },
    bubbleRowWrap: {
      width: '100%',
      alignSelf: 'stretch',
    },
    bubbleRowScroll: {
      width: '100%',
    },
    bubbleRowContent: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 16,
      gap: 14,
      flexGrow: 1,
      justifyContent: 'center',
    },
    bubbleItem: {
      width: 104,
      alignItems: 'center',
    },
    bubbleAvatarOuter: {
      width: 100,
      height: 100,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bubbleCircle: {
      width: 96,
      height: 96,
      borderRadius: 48,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.surface,
      borderWidth: 4,
      borderColor: c.borderStrong,
      shadowColor: c.cardShadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    bubbleCircleActive: {
      borderColor: c.primary,
      borderWidth: 4,
      backgroundColor: c.surfaceMuted,
      shadowOpacity: 0.16,
    },
    bubbleCirclePressed: {
      opacity: 0.92,
    },
    bubbleCamBadge: {
      position: 'absolute',
      right: 0,
      bottom: 0,
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: c.surface,
    },
    bubbleName: {
      fontSize: 16,
      fontWeight: '800',
      color: c.text,
      marginTop: 12,
      textAlign: 'center',
      maxWidth: 104,
    },
    bubbleNamePressed: {
      opacity: 0.85,
    },
    bubbleSub: {
      fontSize: 12,
      fontWeight: '600',
      color: c.primaryDark,
      marginTop: 3,
      textAlign: 'center',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
    },
    modalBackdrop: {
      flex: 1,
    },
    modalSheet: {
      backgroundColor: c.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 18,
      paddingBottom: 28,
      borderWidth: 2,
      borderColor: c.borderStrong,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: c.text,
      marginBottom: 6,
    },
    modalSub: {
      fontSize: 14,
      color: c.textSecondary,
      lineHeight: 20,
      marginBottom: 16,
    },
    presetGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 16,
    },
    presetCell: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: c.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    presetCellSelected: {
      borderColor: c.primary,
      backgroundColor: c.surface,
    },
    presetEmoji: {
      fontSize: 28,
    },
    photoButton: {
      backgroundColor: c.primary,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: 'center',
      marginBottom: 10,
    },
    photoButtonText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 16,
    },
    libraryButton: {
      backgroundColor: c.surface,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: 'center',
      marginBottom: 10,
      borderWidth: 2,
      borderColor: c.primary,
    },
    libraryButtonText: {
      color: c.primary,
      fontWeight: '700',
      fontSize: 16,
    },
    modalCancel: {
      paddingVertical: 12,
      alignItems: 'center',
    },
    modalCancelText: {
      fontSize: 16,
      fontWeight: '600',
      color: c.textSecondary,
    },
  });
}
